### ISSUE TITLE
некорректная кодировка при экспорте цитирования в BibTeX

### ISSUE THREAD

**Issue by maslinych** [ymakarov/dataverse#1]
* [ ] При выгрузке цитирования датасета в BibTeX кодировка сломана. 
        Шаги для воспроизведения: 1. см. датасет, например, 
        https://dataverse.pushdom.ru/dataset.xhtml?persistentId=doi:10.31860/openlit-2019.11-C001
        2. Нажать «Цитировать датасет»
        3. Выбрать из выпадающего списка BibTeX
        4. => Открытый BibTeX-фрагмент в некорректной кодировке.

**Comment by ymakarov** [comment]
Поправил
